resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/0.yaml

allow-newer: true

packages:
  - .
  - "../proto3-wire"

nix:
  packages:
    - zlib.dev
    - zlib.out
