name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  nix-build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        compiler:
          - ghc8104
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: cachix/install-nix-action@v13
        name: Install Nix
      - run: nix-build --attr proto3-suite --argstr compiler "${{ matrix.compiler }}" --arg enableDhall true

  cabal-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["8.10.4"]
        cabal: ["3.6.2.0"]
        os: [ubuntu-latest, macOS-latest]
    name: build and test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: |
          cabal build all
          mkdir gen
          for proto in $(find test-files -name 'test_*.proto'); do
            cabal run compile-proto-file -- --out gen --includeDir test-files --proto "${proto#test-files/}"
          done
          cabal build --enable-tests && cabal test
